### ISSUE TITLE
[AtoNodeRED] Encender Luz Comedor al ponerse el sol y apagarse a las 11 pm

### ISSUE THREAD

**Issue by jolmav** [domoticafacilconjota/capitulos#15]
**Código de la automatización**

```
### ENCENDER LUZ COMEDOR ###  

- id: '1595768602583'
  alias: Encender Luz Comedor
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.luz_comedor
    state: 'off'
  action:
  - data: {}
    entity_id: switch.luz_comedor
    service: switch.turn_on
    
### APAGAR LUZ COMEDOR ###    
    
  mode: single
- id: '1595769527361'
  alias: Apagar Luz Comedor
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.luz_comedor
    state: 'on'
  action:
  - data: {}
    entity_id: switch.luz_comedor
    service: switch.turn_off
  mode: single
```

**Explicación de lo que hace actualmente la automatización**
Estas automatizaciones lo que hacen es lo siguiente:

1.  La primera, enciende la luz del comedor al ponerse el sol, si está apagada
2.  La segunda, apaga la luz del comedor a las 11 de la noche, si está encendida

**Notas del autor**
Podría agregarse que si alguien la enciende después de las 11, se apague 30 minutos después si la dejan encendida.
