### ISSUE TITLE
[AtoNodeRED] Nombre descriptivo

### ISSUE THREAD

**Issue by domoticafacilconjota** [domoticafacilconjota/capitulos#2]
**Código de la automatización**
```
#########################################
##                                     ##
##           FUERA DE CASA 1H          ##
##                                     ##
#########################################
- id: "fuera de casa una hora"
  alias: 'Fuera de casa (+1 Hora)'
  trigger:
    platform: state
    entity_id: sensor.lalu_en_casa
    from: 'yes'
    to: 'no'
    for: '01:00:00'
  action:
   - entity_id: input_boolean.fuera_de_casa_horas
     service: input_boolean.turn_on
```
**Explicación de lo que hace actualmente la automatización**
Esta automatización activa un input boolean cuando estoy fuera de casa más de una hora.

**Notas del autor**
Ejemplo de nota del autor...
