### ISSUE TITLE
Manejo Iluminación Dormitorio 

### ISSUE THREAD

**Issue by Nancho1950** [domoticafacilconjota/capitulos#20]
**Código de la automatización**
```
- id: '1603846567316'
  alias: 'Mesita #1'
  description: 'Enciende y apaga Mesita de noche #1'
  trigger:
  - platform: device
    domain: mqtt
    device_id: d0c248fc0a7311eb8ac4bd3e4b327c07
    type: action
    subtype: single
    discovery_id: 0x00158d000450b798 action_single
  condition: []
  action:
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#1
    domain: light
  mode: single
- id: '1603846764866'
  alias: 'Mesita #2'
  description: 'Enciende y apaga Mesita de noche #2'
  trigger:
  - platform: device
    domain: mqtt
    device_id: 531d50760bee11ebabb7f953763782dc
    type: action
    subtype: single
    discovery_id: 0x00158d000450b761 action_single
  condition: []
  action:
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#2
    domain: light
  mode: single
- id: '1603846964929'
  alias: 'Mesita #1 y Mesita #2'
  description: 'Enciende y apaga Mesita de noche #1 y Mesita de noche #2'
  trigger:
  - platform: device
    domain: mqtt
    device_id: d0c248fc0a7311eb8ac4bd3e4b327c07
    type: action
    subtype: double
    discovery_id: 0x00158d000450b798 action_double
  - platform: device
    domain: mqtt
    device_id: 531d50760bee11ebabb7f953763782dc
    type: action
    subtype: double
    discovery_id: 0x00158d000450b761 action_double
  condition: []
  action:
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#1
    domain: light
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#2
    domain: light
  mode: single
- id: '1603847207830'
  alias: 'Mesita #1, Mesita #2 y Lampara'
  description: 'Enciende y apaga Mesita de noche #1, Mesita de noche #2 y Lampara
    de techo'
  trigger:
  - platform: device
    domain: mqtt
    device_id: d0c248fc0a7311eb8ac4bd3e4b327c07
    type: action
    subtype: hold
    discovery_id: 0x00158d000450b798 action_hold
  - platform: device
    domain: mqtt
    device_id: 531d50760bee11ebabb7f953763782dc
    type: action
    subtype: hold
    discovery_id: 0x00158d000450b761 action_hold
  condition: []
  action:
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#1
    domain: light
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#2
    domain: light
 - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light#3
    domain: light
  mode: single
```

**Explicación de lo que hace actualmente la automatización**
Un clip "single" en el interruptor inalambrico de la mesita #1 enciende la lampara de noche de esa mesita, un doble clip enciende ambas lamparas en la mesita #1 y la mesita #2 o mantener el interruptor "hold" enciende ambas lamparas de las mesitas y la lampara principal de la habitacion, lo mismo si esto se realiza con el interruptor de la mesita #2. Para apagar solo se debe realizar la misma accion en cualquiera de los interruptores. (single, doble o hold.)
**Notas del autor**
El hardware usado es dos interruptores inalambricos aquara modelo WXKG11LM y tres ampolletas xiaomi modelo ZNLDP12LM todos con protocolo zigbee.
