### ISSUE TITLE
[AtoNodeRED]Control de Luz de la salita

### ISSUE THREAD

**Issue by Nancho1950** [domoticafacilconjota/capitulos#21]
**Código de la automatización**
```
- id: '1602283635834'
  alias: Encender / Apagar  Manual
  description: Desactiva las automatizaciones por movimientos y pasa el sistema a
    manual.
  trigger:
  - platform: device
    domain: mqtt
    device_id: d0c248fc0a7311eb8ac4bd3e4b327c07
    type: action
    subtype: single
    discovery_id: 0x00158d000450b798 action_single
  condition: []
  action:
  - type: toggle
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light
    domain: light
  - service: automation.turn_off
    data: {}
    entity_id: automation.centinela
  - service: automation.turn_off
    data: {}
    entity_id: automation.turn_the_light_on_when_motion_is_detected
  mode: single
- id: '1602285296839'
  alias: Enciende al atardecer sin hay movimiento
  description: Enciende la luz por la tarde cuando hay movimiento
  trigger:
  - platform: device
    domain: binary_sensor
    entity_id: binary_sensor.movimiento_occupancy
    device_id: a72089e20a7311eb9994e3b6f09595af
    type: motion
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: time
    after: '16:30:00'
    before: '23:30:00'
  - condition: and
    conditions:
    - condition: sun
      after: sunset
  action:
  - type: turn_on
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light
    domain: light
    flash: short
    brightness_pct: 100
  mode: single
- id: '1602302233727'
  alias: Centinela
  description: Observa si hay movimiento.
  trigger:
  - platform: time_pattern
    minutes: /3
  condition:
  - type: is_no_motion
    condition: device
    device_id: a72089e20a7311eb9994e3b6f09595af
    entity_id: binary_sensor.movimiento_occupancy
    domain: binary_sensor
  - condition: and
    conditions:
    - condition: device
      type: is_on
      device_id: d21be7620a7311eba8b1978a04c92df0
      entity_id: light.lampara_light
      domain: light
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.lampara_light
  mode: single
- id: '1602305727370'
  alias: Desactiva y Activa
  description: apaga la luz y desactiva las actualizaciones y las activa para iniciar
    el ciclo.
  trigger:
  - platform: time
    at: '23:45:00'
  - platform: time
    at: '16:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: d21be7620a7311eba8b1978a04c92df0
    entity_id: light.lampara_light
    domain: light
  - service: automation.toggle
    data: {}
    entity_id: automation.centinela
  - service: automation.toggle
    data: {}
    entity_id: automation.turn_the_light_on_when_motion_is_detected
  mode: single

```
**Explicación de lo que hace actualmente la automatización**
La automiatizacion Enciende la luz de la sala , si el sol se entra y hay movimiento en la sala entre las 16 y las 23:45,
 la automatizacion Centinela monitorea cada 10 minutos si hay moviemto en la sala, de no haberlo apaga la luz. La luz se enciende nuevamente si hay movimiento. Estos ciclos pueden dejar de ser automaticos y pasarlos a manual al dar clip a un interruptor inalambrico para ser controlado de manera manual. De no usar la funcion manual, al termino del horario 23:45 se ejecuta la automatizacion Activa/desactiva apgando la luz de estar encendida y desactivando las automatizaciones de encendido por movimiento y la centinela, para activarlas nuevamente a las 16 hrs, para iniciar nuevamente el ciclo.
**Notas del autor**
El hardware usado es u  sensor de movimiento aqara modelo RTCGQ11LM, un interuptor inalambrico aqara modelo WXKG11LM y una lampara xiomi modelo ZNLDP12LM todas ellas con protocolo zigbee.
