### ISSUE TITLE
[AtoNodeRED] Apagar todo si ambos estamos fuera de casa

### ISSUE THREAD

**Issue by jolmav** [domoticafacilconjota/capitulos#24]
**Código de la automatización**

```
alias: Apagar si ambos estamos fuera de casa
description: ''
trigger:
  - entity_id: group.perez_family_home
    platform: state
    to: not_home
condition:
  - after: sunrise
    before: sunset
    condition: sun
action:
  - data: {}
    entity_id: light.luz_dormitorio_principal
    service: light.turn_off
  - data: {}
    entity_id: light.luz_bano_principal
    service: light.turn_off
  - data: {}
    entity_id: climate.aire_acondicionado
    service: climate.turn_off
  - data: {}
    entity_id: switch.audio
    service: switch.turn_off
  - data: {}
    entity_id: switch.claro
    service: switch.turn_off
  - data: {}
    entity_id: switch.tv
    service: switch.turn_off
mode: single
```

**Explicación de lo que hace actualmente la automatización**

Esta automatización lo que hace es apagar todos los dispositivos indicados, si mi esposa y yo no estamos en casa, pero solo se ejecutará después del amanecer y antes del atardecer

**Notas del autor**

La cantidad de dispositivos dependerá de la necesidad del usuario.
