### ISSUE TITLE
[AtoNodeRED] encender y apagar enchufe termo tramo horario

### ISSUE THREAD

**Issue by monti2222** [domoticafacilconjota/capitulos#26]
**Código de la automatización**
```
  alias: Encender Termo
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition: []
  action:
  - type: turn_on
    device_id: bb20fb90d5fd5b67a2d13404e9e4bebd
    entity_id: switch.enchufe_termo
    domain: switch
  mode: single
- id: '1603924505337'
  alias: Apagar Termo
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - type: turn_off
    device_id: bb20fb90d5fd5b67a2d13404e9e4bebd
    entity_id: switch.enchufe_termo
    domain: switch
  mode: single
```
**Explicación de lo que hace actualmente la automatización**
Enciende el enchufe del termo a las 18:00 y lo apaga a las 22:00

**Notas del autor**
Es bastante sencilla, pero creo que nos ayudaría a los mas novatos a entender mejor como funciona.
Saludos a todos, xD
