### ISSUE TITLE
[AtoNodeRED] Mensaje a la APP o a Telegram de que Home Assistant ha iniciado

### ISSUE THREAD

**Issue by fjterrada69** [domoticafacilconjota/capitulos#31]
**Código de la automatización**
```
- id: '1604933637567'
  alias: HA iniciado
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.mobile_app_redmi_note_7
    data:
      title: HA init
      message: Home Assistant ha comenzado una nueva sesión a las {{ as_timestamp(now())|
        timestamp_local}}.
  mode: single
```

**Explicación de lo que hace actualmente la automatización**
Esta automatización envía una notificación a la APP de HA con el fecha y la hora de cuando a iniciado HA y funciona perfectamente.
**Notas del autor**
En node-red hHe creado un flow con el nodo "event:all" y en el "event type" he colocado "homeassistant_start" pero no me da salida al iniciar HA.
