### ISSUE TITLE
[AtoNodeRED] Temporizador Bicis

### ISSUE THREAD

**Issue by unpunto** [domoticafacilconjota/capitulos#75]
**Código de la automatización**
```
- id: '1640939786196'
  alias: Revisión de calefacción
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition:
  - condition: state
    entity_id: climate.calefaccion
    state: auto
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.calefaccion
    data:
      hvac_mode: auto
  mode: single
```

**Explicación de lo que hace actualmente la automatización**
Revisa cada 15min si la calefacción está en automático y la vuele a poner en automático

**Notas del autor**
Ejemplo notas del autor
